/*
  SCRIPT:   ADD_TABLE.SQL
  OBJETIVO: CRIAR TABELA,INDICE COM SEUS STORAGES
  AUTOR:    JOSIVAN
  DATA:     

  VER O ARQUIVO PARTICAO.SQL, IOT.SQL, PARALLEL.SQL

  ALTER TABLE COMPONENTE
  ADD CONSTRAINT PK_COMPONENTE PRIMARY KEY ( COMPONENTE )
  USING INDEX TABLESPACE MONITORA_IX

*/

------------------------------------------------------------------------------------------
1-movendo uma tabela nao particionada que pertence a tablespace TS_EDGE para outro tablespace

ALTER TABLE EDGE.TBEDGE_AUTORIZACAO
MOVE TABLESPACE TS_EDGE_DADOS;

2-recriar os indices para evitar o erro ORA-01502


------------------------------------------------------------------------------------------
1-movendo uma coluna de uma tabela no oracle 8i

  ALTER TABLE TBEDGE_CLIENTES 
  DROP COLUMN NM_CLIENTE 
  CASCADE CONSTRAINTS CHECKPOINT 1000;

obs: a opcao CHECKPOIN 1000 forca um checkpoint a cada 1000 linhas minimizando a utilizacao
     dos segmentos de rollback.

2-se ocorrer problema durante a operacao a tabela eh marcada como INVALID e a operacao devera
  ser concluida com:

  ALTER TABLE TBEDGE_CLIENTES 
  DROP COLUMNS CONTINUE;

------------------------------------------------------------------------------------------

1-marcar uma coluna como nao usada

  ALTER TABLE TBEDGE_CLIENTES
  SET UNUSED COLUMN NM_CLIENTE
  CASCADE CONSTRAINTS;

2-eliminar colunas nao usadas

  ALTER TABLE TBEDGE_CLIENTES
  DROP UNUSED COLUMNS CHECKPOINTS 1000;

3-continuar a operacao de eliminacao de colunas

  ALTER TABLE TBEDGE_CLIENTES
  DROP COLUMNS CONTINUE CHECKPOINT 1000;

------------------------------------------------------------------------------------------

1-removendo linhas duplicadas de uma tabela.

delete from cliente inst1
where rowid > ( select min(rowid) 
                  from cliente inst2
                 where inst2.pk = inst1.pk);

------------------------------------------------------------------------------------------
 CREATE TABLE AUTORIZACOES
 ( CD_CODIGO_AUT         CHAR(10)
  ,NM_USUARIO_AUT        VARCHAR2(30)
  ,CD_SENHA_AUT          CHAR(8)
  ,CD_SETOR_AUT          CHAR(10)
  ,IC_AUTOR_TOTAL_AUT    NUMBER(1, 0)
  ,CD_AUTORIZACAO1_AUT   CHAR(10)
  ,CD_AUTORIZACAO2_AUT   CHAR(10)
  ,CD_AUTORIZACAO3_AUT   CHAR(10)
  ,CD_AUTORIZACAO4_AUT   CHAR(10)
  ,CD_AUTORIZACAO5_AUT   CHAR(10)
  ,CD_AUTORIZACAO6_AUT   CHAR(10)
  ,CD_AUTORIZACAO7_AUT   CHAR(10)
  ,CD_AUTORIZACAO8_AUT   CHAR(10)
  ,CD_AUTORIZACAO9_AUT   CHAR(10)
  ,CD_AUTORIZACAO10_AUT  CHAR(10)
  ,IC_GRUPO_AUT          NUMBER(1, 0)
  ,CD_REFERENCIA_AUT     VARCHAR2(15)
  ,IC_PRIVILEGIO_AUT     NUMBER(1, 0)
  ,IC_ANALCRIT_AUT       NUMBER(1, 0)
  ,IC_AUTTOTSIST_AUT     NUMBER(1, 0) ) 
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
   STORAGE( INITIAL 30720 
               NEXT 16384
         MINEXTENTS 1
         MAXEXTENTS 121
        PCTINCREASE 50
          FREELISTS 1 
    FREELIST GROUPS 1 )
   TABLESPACE TS_HLP_DADOS1
/

 
CREATE UNIQUE INDEX PK_AUTORIZACOES_AUT ON AUTORIZACOES 
(CD_CODIGO_AUT )
 PCTFREE 10
 INITRANS 2
 MAXTRANS 255
 STORAGE( INITIAL 10240
          NEXT 10240
          MINEXTENTS 1
          MAXEXTENTS 121
          PCTINCREASE 50
          FREELISTS 1 ) 
 TABLESPACE TS_HLP_DADOS1
/


 CREATE TABLE CHAMADOS
 (CD_CHAMADO_CHM        NUMBER(7, 0)
 ,CD_EQUIPAMENTO_CHM    CHAR(9)
 ,NM_SOLICITANTE_CHM    VARCHAR2(15)
 ,CD_ESPECIFICACAO_CHM  VARCHAR2(15)
 ,CD_AREA_ATUACAO_CHM   VARCHAR2(15)
 ,CD_PRIORIDADE_CHM     VARCHAR2(15)
 ,CD_ATENDENTE_CHM      VARCHAR2(15)
 ,DT_ATENDIMENTO_CHM    DATE
 ,HR_ATENDIMENTO_CHM    DATE
 ,CD_PROVIDENCIA1_CHM   VARCHAR2(15)
 ,DT_PROVIDENCIA1_CHM   DATE
 ,HR_PROVIDENCIA1_CHM   DATE
 ,CD_PROVIDENCIA2_CHM   VARCHAR2(15)
 ,DT_PROVIDENCIA2_CHM   DATE
 ,HR_PROVIDENCIA2_CHM   DATE
 ,DS_DESCRICAO_CHM      VARCHAR2(800)
 ,DS_PROVIDENCIA_CHM    VARCHAR2(800)
 ,CD_STATUS_CHM         VARCHAR2(15)
 ,MM_ATENDIMENTO_CHM    NUMBER(6, 0)
 ,MM_PROVIDENCIA1_CHM   NUMBER(6, 0)
 ,MM_PROVIDENCIA2_CHM   NUMBER(6, 0)
 ,MM_ENCERRA_CHM        NUMBER(6, 0)
 ,CD_REFERENCIA_CHM     VARCHAR2(15)
 ,CD_CHAMADO_ANT_CHM    NUMBER(7, 0)
 ,DT_PROVIDENCIA1FIM_CHM DATE
 ,HR_PROVIDENCIA1FIM_CHM DATE
 ,DT_PROVIDENCIA2FIM_CHM DATE
 ,HR_PROVIDENCIA2FIM_CHM DATE
 ,IC_CIENTE1_CHM      NUMBER(1, 0)
 ,IC_CIENTE2_CHM      NUMBER(1, 0)
 ,CD_SIGLA_CHM        CHAR(7)
 ,DS_PRAZO_CHM        NUMBER(6, 0)
 ,IC_ANALCRIT_CHM     NUMBER(1, 0)
 ,CD_ANALIZADO_CHM    VARCHAR2(15)
 ,IC_VIAS_CHM         NUMBER(2, 0)
 ,CD_CIENTEGER_CHM    VARCHAR2(15))
 PCTFREE 10 
 PCTUSED 40 
 INITRANS 1 
 MAXTRANS 255 
 STORAGE(INITIAL 9840640
            NEXT 4909056
      MINEXTENTS 1
      MAXEXTENTS 121 
     PCTINCREASE 50 
       FREELISTS 1 
 FREELIST GROUPS 1)
TABLESPACE TS_HLP_DADOS1;


  CREATE UNIQUE INDEX PK_CHAMADO_CHM
             ON CHAMADOS(CD_CHAMADO_CHM) 
        PCTFREE 10
       INITRANS 2 
       MAXTRANS 255
STORAGE(INITIAL 266240
           NEXT 126976
     MINEXTENTS 1 
     MAXEXTENTS 121
    PCTINCREASE 50 
      FREELISTS 1) 
TABLESPACE TS_HLP_DADOS1;

CREATE INDEX FK_CHAMADO_ANT_CHM
          ON CHAMADOS( CD_EQUIPAMENTO_CHM
                      ,CD_CHAMADO_CHM )
         PCTFREE 10
        INITRANS 2
        MAXTRANS 255
STORAGE( INITIAL 593920
            NEXT 286720
      MINEXTENTS 1
      MAXEXTENTS 121 
     PCTINCREASE 50 
       FREELISTS 1)
TABLESPACE TS_HLP_DADOS1;

CREATE INDEX FK_SIGLA_CHM
          ON CHAMADOS (CD_SIGLA_CHM, CD_CHAMADO_CHM )
        PCTFREE 10
       INITRANS 2
       MAXTRANS 255
STORAGE(INITIAL 593920
           NEXT 286720
     MINEXTENTS 1
     MAXEXTENTS 121
    PCTINCREASE 50
      FREELISTS 1 ) 
TABLESPACE TS_HLP_DADOS1 ;

CREATE INDEX FK_STATUS_CHM ON CHAMADOS(CD_STATUS_CHM ) 
PCTFREE 10
INITRANS 2 
MAXTRANS 255 
STORAGE(INITIAL 593920
           NEXT 286720 
     MINEXTENTS 1 
     MAXEXTENTS 121 
    PCTINCREASE 50 
      FREELISTS 1) 
TABLESPACE TS_HLP_DADOS1;

CREATE TABLE CONJUNTOS
(CD_EQUIPAMENTO_CON  CHAR(9)
,CD_FLOPPYA_CON      VARCHAR2(15)
,CD_FLOPPYB_CON      VARCHAR2(15)
,CD_DISCO1_CON       VARCHAR2(15)
,CD_DISCO2_CON       VARCHAR2(15)
,CD_MEMORIA_CON      VARCHAR2(15)
,CD_UNID_FITA_CON    VARCHAR2(15)
,CD_CD_ROM_CON       VARCHAR2(15)
,CD_FAX_MODEM_CON    VARCHAR2(15)
,CD_LINIATA_CON      CHAR(6)
,CD_HOST_CON         CHAR(16)
,CD_IP_ADDRESS_CON   CHAR(16)
,CD_PORTA_CON        NUMBER(4, 0))
 PCTFREE 10
 PCTUSED 40
 INITRANS 1
 MAXTRANS 255
 STORAGE(INITIAL 112640
            NEXT 55296
      MINEXTENTS 1 
      MAXEXTENTS 121
     PCTINCREASE 50 
       FREELISTS 1 
 FREELIST GROUPS 1) 
TABLESPACE TS_HLP_DADOS1;

CREATE UNIQUE INDEX PK_CONJUNTOS_CON ON CONJUNTOS(CD_EQUIPAMENTO_CON )
PCTFREE 10 
INITRANS 2 
MAXTRANS 255 
STORAGE(INITIAL 71680 
           NEXT 36864 
     MINEXTENTS 1 
     MAXEXTENTS 121
    PCTINCREASE 50 
      FREELISTS 1) 
TABLESPACE TS_HLP_DADOS1;

CREATE TABLE CONTADORES
(CD_CONTADOR_CTD CHAR(10)
,DS_NUMERO_CTD NUMBER(8, 0))
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
MAXTRANS 255 
STORAGE(INITIAL 10240 
           NEXT 10240 
     MINEXTENTS 1 
     MAXEXTENTS 121 
    PCTINCREASE 50 
      FREELISTS 1 
FREELIST GROUPS 1) 
TABLESPACE TS_HLP_DADOS1;

CREATE UNIQUE INDEX PK_CONTADORES_CTD ON CONTADORES(CD_CONTADOR_CTD )
PCTFREE 10 
INITRANS 2 
MAXTRANS 255 
STORAGE (INITIAL 10240
            NEXT 10240 
      MINEXTENTS 1 
      MAXEXTENTS 121 
     PCTINCREASE 50 
     FREELISTS 1) 
TABLESPACE TS_HLP_DADOS1;

CREATE TABLE EQUIPAMENTOS
(CD_EQUIPAMENTO_EQP    CHAR(9)
,CD_NUM_SERIE_EQP      VARCHAR2(25)
,DT_AQUISICAO_EQP      DATE
,AA_GARANTIA_EQP       NUMBER(2, 0)
,MM_GARANTIA_EQP       NUMBER(2, 0)
,DT_TERMINO_EQP        DATE
,CD_FABRICANTE_EQP     VARCHAR2(15)
,CD_TIPO_EQP           VARCHAR2(15)
,CD_MODELO_EQP         VARCHAR2(15)
,CD_TENSAO_EQP         CHAR(10)
,CD_FORNECEDOR_EQP     VARCHAR2(15)
,DS_OBS_EQPTO_EQP      VARCHAR2(50)
,CD_CONJUNTO_EQP       CHAR(9)
,IC_ESTOQUE_EQP        NUMBER(1, 0)
,IC_DESATIVADO_EQP     NUMBER(1, 0)
,IC_LEASE_EQP          NUMBER(1, 0)
,CD_LINIATA_EQP        CHAR(6)
,CD_HOST_EQP           CHAR(16)
,CD_IP_ADDRESS_EQP     CHAR(16)
,CD_PORTA_EQP          NUMBER(4, 0)
,DT_STAMP_EQP DATE)
 PCTFREE 10 
 PCTUSED 40 
INITRANS 1 
MAXTRANS 255 
STORAGE(INITIAL 593920 
           NEXT 286720 
     MINEXTENTS 1 
     MAXEXTENTS 121 
    PCTINCREASE 50 
      FREELISTS 1 
FREELIST GROUPS 1)
TABLESPACE TS_HLP_DADOS1;

CREATE UNIQUE INDEX PK_EQUIPAMENTO_EQP ON EQUIPAMENTOS(CD_EQUIPAMENTO_EQP )
 PCTFREE 10 
INITRANS 2 
MAXTRANS 255 
STORAGE(INITIAL 174080
           NEXT 83968 
     MINEXTENTS 1 
     MAXEXTENTS 121 
    PCTINCREASE 50 
      FREELISTS 1)
TABLESPACE TS_HLP_DADOS1;

CREATE INDEX FK_CONJUNTO_EQP ON EQUIPAMENTOS(CD_CONJUNTO_EQP )
 PCTFREE 10 
INITRANS 2 
MAXTRANS 255 
STORAGE (INITIAL 174080 
            NEXT 83968 
      MINEXTENTS 1 
      MAXEXTENTS 121 
     PCTINCREASE 50
       FREELISTS 1) 
TABLESPACE TS_HLP_DADOS1;

CREATE INDEX FKCD_NUM_SERIE_EQP ON EQUIPAMENTOS(CD_NUM_SERIE_EQP ) 
 PCTFREE 10 
INITRANS 2 
MAXTRANS 255 
STORAGE (INITIAL 174080 
            NEXT 83968 
      MINEXTENTS 1 
      MAXEXTENTS 121 
     PCTINCREASE 50 
       FREELISTS 1) 
TABLESPACE TS_HLP_DADOS1;

CREATE TABLE EQUIPAMENTOS_TMP
(CD_EQUIPAMENTO_EQP  CHAR(9)
,CD_NUM_SERIE_EQP VARCHAR2(25)
,DT_AQUISICAO_EQP DATE
,AA_GARANTIA_EQP NUMBER(2, 0)
,MM_GARANTIA_EQP NUMBER(2, 0)
,DT_TERMINO_EQP DATE
,CD_FABRICANTE_EQP VARCHAR2(15)
,CD_TIPO_EQP VARCHAR2(15)
,CD_MODELO_EQP VARCHAR2(15)
,CD_TENSAO_EQP CHAR(10)
,CD_FORNECEDOR_EQP VARCHAR2(15)
,DS_OBS_EQPTO_EQP VARCHAR2(50)
,CD_CONJUNTO_EQP CHAR(9)
,IC_ESTOQUE_EQP NUMBER(1, 0)
,IC_DESATIVADO_EQP NUMBER(1, 0)
,IC_LEASE_EQP NUMBER(1, 0))
 PCTFREE 10 
 PCTUSED 40 
INITRANS 1 
MAXTRANS 255 
 STORAGE(INITIAL 593920
            NEXT 286720
      MINEXTENTS 1 
      MAXEXTENTS 121 
     PCTINCREASE 50 
       FREELISTS 1
 FREELIST GROUPS 1) 
TABLESPACE TS_HLP_DADOS1;

 CREATE TABLE ESPECIALIDADES
(CD_CODIGO_ESP CHAR(10)
,CD_ESPECIALIDADE_ESP VARCHAR2(15))
 PCTFREE 10
 PCTUSED 40
INITRANS 1 
MAXTRANS 255
 STORAGE(INITIAL 40960
            NEXT 24576
      MINEXTENTS 1
      MAXEXTENTS 121
     PCTINCREASE 50
       FREELISTS 1 
 FREELIST GROUPS 1)
TABLESPACE TS_HLP_DADOS1;

CREATE UNIQUE INDEX PK_ESPECIALIDADES_ESP ON ESPECIALIDADES(CD_CODIGO_ESP , CD_ESPECIALIDADE_ESP )
 PCTFREE 10 
INITRANS 2
MAXTRANS 255 
STORAGE (INITIAL 71680 
            NEXT 36864 
      MINEXTENTS 1 
      MAXEXTENTS 121 
     PCTINCREASE 50 
       FREELISTS 1) 
TABLESPACE TS_HLP_DADOS1;

CREATE INDEX FKCD_ESPECIALIDADE_ESP ON ESPECIALIDADES(CD_ESPECIALIDADE_ESP )
 PCTFREE 10
INITRANS 2 
MAXTRANS 255 
STORAGE (INITIAL 40960 
            NEXT 24576 
      MINEXTENTS 1 
      MAXEXTENTS 121 
     PCTINCREASE 50 
       FREELISTS 1) 
TABLESPACE TS_HLP_DADOS1;

 CREATE TABLE FABRICANTES
(CD_FABRICANTE VARCHAR2(15)
,NM_FABRICANTE VARCHAR2(60)) 
 PCTFREE 10
 PCTUSED 40
INITRANS 1 
MAXTRANS 255 
 STORAGE(INITIAL 10240 
            NEXT 10240 
      MINEXTENTS 1
      MAXEXTENTS 121 
     PCTINCREASE 50
       FREELISTS 1
 FREELIST GROUPS 1)
TABLESPACE TS_HLP_DADOS1;

CREATE UNIQUE INDEX PK_FABRICANTES_FAB ON FABRICANTES
(CD_FABRICANTE )
  PCTFREE 10
 INITRANS 2 
 MAXTRANS 255
  STORAGE( INITIAL 10240
              NEXT 10240
        MINEXTENTS 1 
        MAXEXTENTS 121
       PCTINCREASE 50 
         FREELISTS 1 ) 
TABLESPACE TS_HLP_DADOS1;

 CREATE TABLE FORNECEDORES
( CD_FORNECEDOR_FOR  VARCHAR2(15)
 ,NM_RAZAO_FOR       VARCHAR2(40)
 ,DS_ENDERECO_FOR    VARCHAR2(40)
 ,DS_BAIRRO_FOR      VARCHAR2(15)
 ,DS_CIDADE_FOR      VARCHAR2(20)
 ,DS_ESTADO_FOR      CHAR(2)
 ,DS_CEP_FOR         CHAR(9)
 ,DS_TELEFONE1_FOR   VARCHAR2(15)
 ,DS_TELEFONE2_FOR   VARCHAR2(15)
 ,DS_FAX_FOR         VARCHAR2(15)
 ,DS_CONTATO_FOR     VARCHAR2(15)
 ,DS_OBS_FOR         VARCHAR2(40))
  PCTFREE 10
  PCTUSED 40
 INITRANS 1 
 MAXTRANS 255
  STORAGE(INITIAL 10240
             NEXT 10240
       MINEXTENTS 1
       MAXEXTENTS 121 
      PCTINCREASE 50
        FREELISTS 1 
  FREELIST GROUPS 1)
 TABLESPACE TS_HLP_DADOS1;

CREATE UNIQUE INDEX PK_FORNECEDORES_FOR ON FORNECEDORES 
(CD_FORNECEDOR_FOR )
 PCTFREE 10 
INITRANS 2 
MAXTRANS 255 
 STORAGE(INITIAL 10240 
            NEXT 10240 
      MINEXTENTS 1
      MAXEXTENTS 121
     PCTINCREASE 50 
       FREELISTS 1) 
TABLESPACE TS_HLP_DADOS1;

 CREATE TABLE INSTALACOES
( CD_EQUIPAMENTO_LOC CHAR(9)
 ,CD_BASE_LOC        CHAR(3)
 ,CD_LOCAL_LOC       VARCHAR2(15)
 ,NM_RESPONSAVEL_LOC VARCHAR2(30)
 ,DS_OBS_LOC         VARCHAR2(50)
 ,DS_RAMAL_LOC       VARCHAR2(20)
 ,CD_HANGAR_LOC      CHAR(1)
 ,CD_SIGLA_LOC       CHAR(7)
 ,IC_REDE_LOC        NUMBER(1, 0)) 
  PCTFREE 10 
  PCTUSED 40 
 INITRANS 1 
 MAXTRANS 255 
  STORAGE(INITIAL 174080 
             NEXT 83968 
       MINEXTENTS 1 
       MAXEXTENTS 121 
      PCTINCREASE 50 
        FREELISTS 1 
  FREELIST GROUPS 1) 
 TABLESPACE TS_HLP_DADOS1;

CREATE UNIQUE INDEX PK_INSTALACOES_LOC ON INSTALACOES 
(CD_EQUIPAMENTO_LOC ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE 
(INITIAL 112640 NEXT 55296 MINEXTENTS 1 MAXEXTENTS 121 PCTINCREASE 50 
FREELISTS 1) TABLESPACE TS_HLP_DADOS1 ;
 CREATE TABLE LICENCA (CD_SOFTWARE_LIC VARCHAR2(15), 
 CD_LICENCA_LIC VARCHAR2(25), QT_LICENCA_LIC NUMBER(3, 0), 
 CD_FORNECEDOR_LIC VARCHAR2(15), CD_NFISCAL_LIC VARCHAR2(10), 
 DT_COMPRA_LIC DATE, VL_UNITARIO_LIC NUMBER(10, 2), 
 DS_OBSERVACAO_LIC VARCHAR2(800)) PCTFREE 10 PCTUSED 40 INITRANS 1 
 MAXTRANS 255 STORAGE(INITIAL 20480 NEXT 16384 MINEXTENTS 1 MAXEXTENTS 
 121 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) TABLESPACE 
 TS_HLP_DADOS1 ;

CREATE UNIQUE INDEX PK_LICENCA_LIC ON LICENCA 
(CD_SOFTWARE_LIC , CD_LICENCA_LIC ) PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE (INITIAL 22528 NEXT 16384 MINEXTENTS 1 MAXEXTENTS 121 PCTINCREASE 
50 FREELISTS 1) TABLESPACE TS_HLP_DADOS1 ;
 CREATE TABLE PARAMETROS (CL_PARAMETRO CHAR(2), 
 CD_PARAMETRO VARCHAR2(15), IC_CONDICAO VARCHAR2(15), 
 IC_EXIBE_COMBO NUMBER(1, 0)) PCTFREE 10 PCTUSED 40 INITRANS 1 
 MAXTRANS 255 STORAGE(INITIAL 71680 NEXT 36864 MINEXTENTS 1 MAXEXTENTS 
 121 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) TABLESPACE 
 TS_HLP_DADOS1 ;

CREATE UNIQUE INDEX PK_PARAMETROS_PAR ON PARAMETROS 
(CL_PARAMETRO , CD_PARAMETRO , IC_CONDICAO ) PCTFREE 10 INITRANS 2 
MAXTRANS 255 STORAGE (INITIAL 174080 NEXT 83968 MINEXTENTS 1 MAXEXTENTS 
121 PCTINCREASE 50 FREELISTS 1) TABLESPACE TS_HLP_DADOS1 ;
 CREATE TABLE SIGLAS (CD_SIGLA_SGL CHAR(7), 
 NM_SIGLA_SGL VARCHAR2(30), DS_RAMAL_SGL VARCHAR2(15), 
 DS_OBS_SGL VARCHAR2(30), CD_BASE_SGL VARCHAR2(3), CD_HANGAR_SGL 
 NUMBER(2, 0)) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 STORAGE(INITIAL 40960 NEXT 24576 MINEXTENTS 1 MAXEXTENTS 121 
 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) TABLESPACE 
 TS_HLP_DADOS1 ;

CREATE UNIQUE INDEX PK_SIGLAS_SGL ON SIGLAS (CD_SIGLA_SGL 
) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE (INITIAL 40960 NEXT 24576 
MINEXTENTS 1 MAXEXTENTS 121 PCTINCREASE 50 FREELISTS 1) TABLESPACE 
TS_HLP_DADOS1 ;
 CREATE TABLE SOFTINSTALADOS (CD_EQUIPAMENTO_SFW 
 CHAR(9), CD_SOFTWARE_SFW VARCHAR2(15), CD_LICENCA_SFW 
 VARCHAR2(25), QT_LICENCA_SFW NUMBER(2, 0)) PCTFREE 10 PCTUSED 40 
 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 266240 NEXT 126976 MINEXTENTS 
 1 MAXEXTENTS 121 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) 
 TABLESPACE TS_HLP_DADOS1 ;

CREATE UNIQUE INDEX PK_SOFTINSTALADOS_SFW ON SOFTINSTALADOS 
(CD_EQUIPAMENTO_SFW , CD_SOFTWARE_SFW ) PCTFREE 10 INITRANS 2 MAXTRANS 
255 STORAGE (INITIAL 399360 NEXT 190464 MINEXTENTS 1 MAXEXTENTS 121 
PCTINCREASE 50 FREELISTS 1) TABLESPACE TS_HLP_DADOS1 ;
CREATE INDEX FK_EQUIPAMENTO_SFW ON SOFTINSTALADOS 
(CD_EQUIPAMENTO_SFW ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE 
(INITIAL 266240 NEXT 126976 MINEXTENTS 1 MAXEXTENTS 121 PCTINCREASE 50 
FREELISTS 1) TABLESPACE TS_HLP_DADOS1 ;

CREATE INDEX FK_LICENCA_SFW ON SOFTINSTALADOS 
(CD_LICENCA_SFW ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE (INITIAL 
174080 NEXT 83968 MINEXTENTS 1 MAXEXTENTS 121 PCTINCREASE 50 FREELISTS 1) 
TABLESPACE TS_HLP_DADOS1 ;
CREATE INDEX FK_SOFTW_LIC_SFW ON SOFTINSTALADOS 
(CD_SOFTWARE_SFW , CD_LICENCA_SFW ) PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE (INITIAL 399360 NEXT 190464 MINEXTENTS 1 MAXEXTENTS 121 
PCTINCREASE 50 FREELISTS 1) TABLESPACE TS_HLP_DADOS1 ;
CREATE INDEX FK_SOFTWARE_SFW ON SOFTINSTALADOS 
(CD_SOFTWARE_SFW ) PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE (INITIAL 
266240 NEXT 126976 MINEXTENTS 1 MAXEXTENTS 121 PCTINCREASE 50 FREELISTS 1) 
TABLESPACE TS_HLP_DADOS1 ;

 CREATE TABLE VERSAO (CD_VERSAO_VER NUMBER(3, 0), 
 DS_LOCAL_VER VARCHAR2(40)) PCTFREE 10 PCTUSED 40 INITRANS 1 
 MAXTRANS 255 STORAGE(INITIAL 10240 NEXT 10240 MINEXTENTS 1 MAXEXTENTS 
 121 PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1) TABLESPACE 
 TS_HLP_DADOS1 ;
