REM  rodar o script UTLXPLAN.sql sob o schema SYS

Set echo off
Set verify off
set pages 1000
set lines 300

Delete from plan_table;
commit;

col operation   format A500
col options     format A15
col object_name format A25
col PARTITION_START format A25
col PARTITION_STOP format A25
set echo on
explain plan for
SELECT ACT.SACT_NUMRA,ABP.SABP_DESC,ACT.SACT_NOTA
, ACT.SACT_COMPARECEU, ACT.SACT_DTAPONT, ACT.SACT_HRAPONT
FROM SEU.SEUACT ACT,
SEU.SEUABP ABP
WHERE
ACT.SACT_NUMRA = ABP.SABP_NUMRA
AND ACT.SACT_IDEMPRESA = :"SYS_B_00"
AND ACT.SACT_IDEMPRESA = ABP.SABP_IDEMPRESA
AND ACT.SACT_NUMRA     = :"SYS_B_01"  AND ACT.SACT_ANOLET    = :"SYS_B_02"
AND ACT.SACT_PERIODO   = :"SYS_B_03"  AND ACT.SACT_CODCUR    = :"SYS_B_04"
AND ACT.SACT_VERSAO    = :"SYS_B_05"
AND ACT.SACT_SERIE     = :"SYS_B_06"
AND ACT.SACT_TPAPONT   = :"SYS_B_07" 
AND ACT.SACT_CODDIS    = :"SYS_B_08"                  
AND ACT.SACT_STATUS    IN (:"SYS_B_09",:"SYS_B_10")  
UNION
SELECT ACT.SACT_NUMRA,ABP.SABP_DESC, ACT.SACT_NOTA, ACT.SACT_COMPARECEU, ACT.SACT_DTAPONT, ACT.SACT_HRAPONT
FROM SEU.SEUACT ACT,
SEU.SEUABP ABP
WHERE
ACT.SACT_NUMRA = ABP.SABP_NUMRA
AND ACT.SACT_IDEMPRESA = :"SYS_B_11"  
AND ACT.SACT_NUMRA= :"SYS_B_12"  
AND ACT.SACT_ANONOVO   = :"SYS_B_13"
AND ACT.SACT_PERNOVO   = :"SYS_B_14"  AND
ACT.SACT_CODCUR    = :"SYS_B_15"
AND ACT.SACT_VERSAO    = :"SYS_B_16"
AND ACT.SACT_SERIE     = :"SYS_B_17"
AND ACT.SACT_TPAPONT   = :"SYS_B_18" 
AND ACT.SACT_CODDIS    = :"SYS_B_19"                  
AND ACT.SACT_STATUS    IN (:"SYS_B_20",:"SYS_B_21")
/
set echo off 
spool explain.lis
select * from table(dbms_xplan.display('PLAN_TABLE',null,'ALL'));
spool off








