SET PAGES 1000
SET LINES 200
SET ECHO OFF
SET VER OFF
accept tabela prompt "Digite o nome da tabela: "
accept owner prompt "Digite o owner da tabela: "
SELECT B.TABLE_NAME, B.CONSTRAINT_NAME FROM DBA_CONSTRAINTS A, DBA_CONSTRAINTS B 
WHERE A.CONSTRAINT_NAME = B.R_CONSTRAINT_NAME 
AND A.TABLE_NAME=upper('&&TABELA')
AND A.OWNER=upper('&&OWNER');
BREAK ON CONSTRAINT_NAME
SELECT A.CONSTRAINT_NAME, A.COLUMN_NAME, A.POSITION FROM DBA_CONS_COLUMNS A,
(SELECT B.TABLE_NAME, B.CONSTRAINT_NAME, B.OWNER FROM DBA_CONSTRAINTS A, DBA_CONSTRAINTS B 
WHERE A.CONSTRAINT_NAME = B.R_CONSTRAINT_NAME 
AND A.TABLE_NAME=upper('&&TABELA')
AND A.OWNER=upper('&&OWNER')) C
WHERE A.OWNER=C.OWNER
AND A.CONSTRAINT_NAME=C.CONSTRAINT_NAME
AND A.TABLE_NAME=C.TABLE_NAME
/