SET PAGES 1000
SET LINES 200
SET ECHO OFF
SET VER OFF
accept tabela prompt "Digite o nome da tabela: "
accept owner prompt "Digite o owner da tabela: "
SELECT DISTINCT A.TABLE_NAME, A.CONSTRAINT_NAME FROM DBA_CONSTRAINTS A, DBA_CONSTRAINTS B 
WHERE A.CONSTRAINT_NAME = B.R_CONSTRAINT_NAME 
AND B.TABLE_NAME=upper('&TABELA')
AND B.OWNER=upper('&OWNER');