set pages 0
set lines 200
set ver off
accept owner prompt "Digite o owner da aplicacao: "

select 'grant '||decode(object_type,'TABLE','SELECT,INSERT,UPDATE,DELETE','SEQUENCE','SELECT','EXECUTE')||' ON '||
OBJECT_NAME||' TO R_&&OWNER._ALL;'
FROM USER_OBJECTS 
WHERE OBJECT_TYPE IN ('TABLE','SEQUENCE','TYPE','FUNCTION','PACKAGE','PROCEDURE')
AND TRUNC(CREATED)=TRUNC(SYSDATE)
UNION
SELECT 'GRANT SELECT ON '||OBJECT_NAME||' TO R_&&OWNER._READ;'
FROM USER_OBJECTS
WHERE OBJECT_TYPE IN ('TABLE','SEQUENCE')
AND TRUNC(CREATED)=TRUNC(SYSDATE);  