
SELECT * FROM X$KGLLK LOCK_A  
 WHERE KGLLKREQ = 0 
   AND EXISTS (SELECT LOCK_B.KGLLKHDL FROM X$KGLLK LOCK_B 
               WHERE KGLLKSES = '&&saddr' /* BLOCKED SESSION */ 
               AND LOCK_A.KGLLKHDL = LOCK_B.KGLLKHDL 
               AND KGLLKREQ > 0); 
 

 SELECT SID,USERNAME,TERMINAL,PROGRAM FROM V$SESSION 
 WHERE SADDR in  
  (SELECT KGLLKSES FROM X$KGLLK LOCK_A  
   WHERE KGLLKREQ = 0 
     AND EXISTS (SELECT LOCK_B.KGLLKHDL FROM X$KGLLK LOCK_B 
                 WHERE KGLLKSES = '&&saddr' /* BLOCKED SESSION */ 
                 AND LOCK_A.KGLLKHDL = LOCK_B.KGLLKHDL 
                 AND KGLLKREQ > 0) 
  ); 
