/*
  SCRIPT:   LST_PRIVS_PROCE.SQL
  OBJETIVO: PRIVILEGIOS
  AUTOR:    JOSIVAN
  DATA:     2000.02.08   
*/

SET ECHO OFF
SET LINESIZE 1500
--
BREAK ON OBJECTO SKIP 1
--
SET PAGESIZE 200
--
SELECT TABLE_NAME OBJECTO
      ,PRIVILEGE  PRIVILEGIO
      ,GRANTEE    DESTINO
  FROM DBA_TAB_PRIVS
 WHERE OWNER IN ('GALPDBA')
   AND TABLE_NAME LIKE 'SP%'
   AND TABLE_NAME IN (SELECT OBJECT_NAME
                        FROM DBA_OBJECTS
                       WHERE OWNER = 'GALPDBA')
/
