/*
  SCRIPT:   LST_STORAGE_TABLE.SQL
  OBJETIVO: LISTAR TODOS OS DADOS DA TABELA: TABLESPACE,PCTFREE,PCTUSED E ETC...
  AUTOR:    JOSIVAN
  DATA:     
*/

SET PAGESIZE 5000

SELECT TABLESPACE_NAME
      ,PCT_FREE
      ,PCT_USED
      ,INITIAL_EXTENT
      ,NEXT_EXTENT
      ,MIN_EXTENTS
      ,MAX_EXTENTS
      ,NUM_ROWS
      ,((BLOCKS*4096)/1024) MB_UTILIZADOS
      ,BLOCKS
      ,((EMPTY_BLOCKS*4096)/1024) MB_LIVRES
      ,AVG_SPACE
      ,AVG_ROW_LEN
      ,AVG_SPACE_FREELIST_BLOCKS
      ,CHAIN_CNT
      ,SAMPLE_SIZE
      ,BUFFER_POOL
  FROM DBA_TABLES
 WHERE OWNER = 'EDGE'    -- TABLE_NAME = '&TABELA'
/
