/*
  SCRIPT:   LST_INDEX.SQL
  OBJETIVO: LISTAR OS INDICES DA TABELA, INFORMAR O OWNER E TABLE
  AUTOR:    JOSIVAN
  DATA:     2000.02.08   
*/

SELECT INDEX_NAME
      ,INDEX_TYPE
      ,TABLESPACE_NAME
      ,PCT_FREE
      ,LEAF_BLOCKS
      ,NUM_ROWS
      ,DISTINCT_KEYS
      ,STATUS
      ,SAMPLE_SIZE
      ,LAST_ANALYZED
      ,GENERATED 
  FROM ALL_INDEXES
 WHERE OWNER      = '&DONO'
   AND TABLE_NAME = '&TABELA'
/
