/*
  SCRIPT:   OBJ_ACESSO.SQL
  OBJETIVO: VERIFICAR O ACESSO CONCEDIDO PARA OUTROS USUARIOS, COMPARANDO AS TABELAS DO
            OWNER COM OS DEMAIS USERS
  AUTOR:    JOSIVAN
  DATA:     2000.02.09   
*/

SET ECHO OFF
SET LINESIZE 1500
SET PAGESIZE 200
--
BREAK ON TIPO SKIP 1
--
SELECT OBJECT_NAME OBJECTOS_GALP
      ,OBJECT_TYPE TIPO
  FROM DBA_OBJECTS
 WHERE OWNER = 'GALPDBA'
   AND OBJECT_TYPE IN ('TABLE','PROCEDURE','VIEW','PACKAGE')
   AND OBJECT_NAME NOT IN (SELECT OBJECT_NAME
                             FROM DBA_OBJECTS
                            WHERE OWNER IN('GALP'))
/

SELECT OBJECT_NAME OBJECTOS_GALP
      ,OBJECT_TYPE TIPO
  FROM DBA_OBJECTS
 WHERE OWNER = 'GALPDBA'
   AND OBJECT_TYPE IN ('TABLE','PROCEDURE','VIEW','PACKAGE')
   AND OBJECT_NAME NOT IN (SELECT OBJECT_NAME
                             FROM DBA_OBJECTS
                            WHERE OWNER IN('CONSULTA'))
/

SELECT OBJECT_NAME OBJECTOS_OPS$
      ,OBJECT_TYPE TIPO
  FROM DBA_OBJECTS
 WHERE OWNER = 'GALPDBA'
   AND OBJECT_TYPE IN ('PROCEDURE')
   AND OBJECT_NAME NOT IN (SELECT OBJECT_NAME
                             FROM DBA_OBJECTS
                            WHERE OWNER = 'OPS$PRODUC')
/

SELECT OBJECT_NAME OBJECTOS_TAP
      ,OBJECT_TYPE TIPO
  FROM DBA_OBJECTS
 WHERE OWNER = 'TAPDBA'
   AND OBJECT_TYPE IN ('TABLE','PROCEDURE','VIEW','PACKAGE')
   AND OBJECT_NAME NOT IN (SELECT OBJECT_NAME
                             FROM DBA_OBJECTS WHERE OWNER = 'TAP')
/

SELECT OBJECT_NAME OBJECTOS_TAPOPS$
      ,OBJECT_TYPE TIPO
  FROM DBA_OBJECTS
 WHERE OWNER = 'TAPDBA'
   AND OBJECT_TYPE IN ('PROCEDURE')
   AND OBJECT_NAME NOT IN (SELECT OBJECT_NAME
                             FROM DBA_OBJECTS
                            WHERE OWNER = 'OPS$PRODUC')
/

SELECT OBJECT_NAME OBJECTOS_TAP
      ,OBJECT_TYPE TIPO
  FROM DBA_OBJECTS
 WHERE OWNER = 'GASDBA'
   AND OBJECT_TYPE IN ('TABLE','PROCEDURE','VIEW','PACKAGE')
   AND OBJECT_NAME NOT IN (SELECT OBJECT_NAME
                             FROM DBA_OBJECTS
                            WHERE OWNER = 'GASOLEO')
/

SELECT OBJECT_NAME OBJECTOS_TAPOPS$
      ,OBJECT_TYPE TIPO
  FROM DBA_OBJECTS
 WHERE OWNER = 'GASDBA'
   AND OBJECT_TYPE IN ('PROCEDURE')
   AND OBJECT_NAME NOT IN (SELECT OBJECT_NAME
                             FROM DBA_OBJECTS
                            WHERE OWNER = 'OPS$PRODUC')
/
