SELECT 'CREATE PUBLIC SYNONYM '||SYNONYM_NAME||' FOR '||TABLE_OWNER||'.'||TABLE_NAME||';'

FROM DBA_SYNONYMS A WHERE TABLE_OWNER IN ('FINPAC','FINPAC_INTERF') AND NOT EXISTS

(SELECT 'X' FROM DBA_SYNONYMS@QERP B WHERE B.OWNER=A.OWNER AND B.SYNONYM_NAME=A.SYNONYM_NAME);
