set pages 1000
set lines 200
col output format a130
col status format a15
alter session set nls_date_format='dd/mm/yy hh24:mi';


SELECT SESSION_KEY, SESSION_RECID, STATUS, INPUT_TYPE, START_TIME, END_TIME
, TRUNC(INPUT_BYTES/1024/1024) INPUT_BYTES_MB, TRUNC(OUTPUT_BYTES/1024/1024) OUTPUT_BYTES_MB
FROM V$RMAN_BACKUP_JOB_DETAILS 
ORDER BY START_TIME;

ACCEPT KEY PROMPT "Digite o SESSION_KEY para detalhes: "


select OUTPUT FROM V$RMAN_OUTPUT WHERE SESSION_RECID=&&KEY;



