/*
  SCRIPT:   SCR_COMPILA.SQL
  OBJETIVO: SCRIPT PARA RECUPERAR OS OBJETOS INVALIDOS
  AUTOR:    JOSIVAN
  DATA:     2000.02.08
*/

--
SET PAGESIZE 150
--
SELECT   'ALTER '||OBJECT_TYPE
       ||' '||OWNER
       ||'.'||OBJECT_NAME
       ||' COMPILE;' FROM ALL_OBJECTS
WHERE STATUS = 'INVALID'
/

