/*
  SCRIPT:   SCR_ANALYZE.SQL
  OBJETIVO: SCRIPT PARA ACTUALIZAR AS ESTATISTICAS DA TABELA E INDEX, INFORMAR O OWNER DAS TABELAS
  AUTOR:    JOSIVAN
  DATA:     2000.02.08   
*/

SELECT   'ANALYZE TABLE '
       ||OWNER
       ||'.'
       ||TABLE_NAME
       ||' COMPUTE STATISTICS;'
  FROM ALL_TABLES
 WHERE OWNER = '&DONO'
   AND (NUM_ROWS IS NULL OR TO_CHAR(LAST_ANALYZED,'DD.MM.YYYY') < TO_CHAR(SYSDATE - 2,'DD.MM.YYYY'))
/

ANALYSE TABLE TRANS_ABAST ESTIMATE STATISTICS SAMPLE 20 PERCENT;
ANALYZE TABLE TRANS_ABAST COMPUTE STATISTICS;

--
-- PARA INDEX
--
SELECT   'ANALYZE INDEX '
       ||OWNER
       ||'.'
       ||INDEX_NAME
       ||' COMPUTE STATISTICS;'
  FROM ALL_INDEXES
 WHERE OWNER = '&DONO'
   AND (NUM_ROWS IS NULL OR TO_CHAR(LAST_ANALYZED,'DD.MM.YYYY') < TO_CHAR(SYSDATE - 2,'DD.MM.YYYY'))
/

analyze index EMIS_EMIOCO_AER_1 compute statistics;
analyze index IND_ADV_AER_1 compute statistics;
analyze index IND_AER_FUNEMP_1 compute statistics;
analyze index GALPDBA.PK_INFOR_GESTA_TRANS  estimate statistics sample 20 percent;