SELECT A.OCORCOD||' '||LPAD(A.OCORPRIOR,2,'0')||
' '||A.OCORSTATUS||' '||LPAD(SUBSTR(A.NNUM_CART,1,4),4,'0')||
'.'||LPAD(SUBSTR(A.NNUM_CART,5,4),4,'0')||'.'||LPAD(SUBSTR(A.NNUM_CART,9,4),4,'0')||
'.'||LPAD(SUBSTR(A.NNUM_CART,13,4),4,'0')||' '||SUBSTR(B.PRODDESC,1,5)||
' '||SUBSTR(C.PROBDESC,1,5)||' '||SUBSTR(A.OCORDTLIG,7,2)||'/'||SUBSTR(A.OCORDTLIG,5,2)||
'/'||SUBSTR(A.OCORDTLIG,1,4)||' '||A.OCORHRLIG||' '||NVL(LPAD(A.OCORAGEN,5,'0'),'00000')||
' '||NVL(LPAD(A.OCORCONTA,7,'0'),'0000000')||'-'||NVL(RPAD(A.OCORDIGCON,1,'0'),0)||
' '||RPAD(A.OCORNOOPER,10,' ')||' '||A.OCORNOANA||TO_CHAR(D.DDATAHORA,'DD/MM/YYYY HH24:MI')
FROM TBEDGE_OCORPEND00 A, 
     TBEDGE_PRODUTO B, 
     TBEDGE_PROBLEMA C,
     TBEDGE_LOG_BACK D
WHERE A.OCORCOD  = 1101726064 
  AND A.OCORPROD = B.PRODCOD 
  AND A.OCORPROB = C.PROBCOD
  AND A.OCORCOD = D.NNOCORR(+);