/*
  SCRIPT:   TS_GRAU.SQL
  OBJETIVO: NIVEL DE FRAGMENTACAO DO ESPACO LIVRE DAS TABLESPACES
  AUTOR:    JOSIVAN
  DATA:     
*/

CLEAR SCREEN

  SELECT TABLESPACE_NAME
        ,COUNT(*)  "GRAU FRAGMENTACAO LIVRE"
    FROM DBA_FREE_SPACE
GROUP BY TABLESPACE_NAME
ORDER BY 2 DESC
/
