create or replace view seu.seuaef
(SAEF_IDEMPRESA      
,SAEF_COD            
,SAEF_AGENCIA        
,SAEF_NOMEAGE        
,SAEF_NUMCON         
,SAEF_NOME           
,SAEF_NREDUZ         
,SAEF_END            
,SAEF_BAIRRO         
,SAEF_MUN            
,SAEF_CEP            
,SAEF_EST            
,SAEF_TEL            
,SAEF_FAX            
,SAEF_TELEX          
,SAEF_CONTATO        
,SAEF_DEPTO          
,SAEF_RETENCA        
,SAEF_RETDESC        
,SAEF_SALANT         
,SAEF_SALATU         
,SAEF_TXCOBSI        
,SAEF_TXCOBDE        
,SAEF_TAXADES        
,SAEF_LAYOUT         
,SAEF_CONTA          
,SAEF_BOLETO         
,SAEF_MENSAGE        
,SAEF_LAYIPMF        
,SAEF_IMPFISC        
,SAEF_GAVETA         
,SAEF_DINHEIR        
,SAEF_CHEQUES        
,SAEF_CARTAO         
,SAEF_CONVENI        
,SAEF_VALES          
,SAEF_FINANC         
,SAEF_OUTROS         
,SAEF_VLRDEBI        
,SAEF_OK             
,SAEF_FLUXCAI        
,SAEF_DIASCOB        
,SAEF_DATAABR        
,SAEF_DATAFCH        
,SAEF_HORAFCH        
,SAEF_HORAABR        
,SAEF_TEF            
,SAEF_LIMCRED        
,SAEF_UNIDFED        
,SAEF_COD_P          
,SAEF_TAXA           
,SAEF_CMC7           
,SAEF_FLSERV         
,SAEF_MOEDA          
,SAEF_SALANT2        
,SAEF_CONTABI        
,SAEF_SALATU2        
,SAEF_COD_BC         
,SAEF_REMOTO         
,SAEF_CODCLI         
,SAEF_CODFOR         
,SAEF_CXPOSTA        
,SAEF_LOJCLI         
,SAEF_LOJFOR         
,SAEF_MOEDAP         
,SAEF_PAISBCO        
,SAEF_NUMBCO         
,SAEF_CORRENT        
,SAEF_BORD           
,SAEF_USERLGI        
,SAEF_USERLGA        
,SAEF_DIGIPOR        
,SAEF_ESPECIE        
,SAEF_ACEITE         
,SAEF_CART           
,SAEF_OBS            
,SAEF_D_E_L_E_T_          
,SAEF_R_E_C_N_O_
,SAEFA6_CALDIG )        
AS SELECT * FROM SIGA.SA6010
/  
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      
                      