SELECT 	U.USERNAME, 
	A.EXECUTIONS, 
	P.COST, 
	A.SQL_TEXT
FROM 	V$SQLAREA A, 
	V$SQL_PLAN P, 
	DBA_USERS U
WHERE 	P.ADDRESS=A.ADDRESS
AND 	A.PARSING_USER_ID=U.USER_ID
AND 	A.HASH_VALUE=P.HASH_VALUE
AND 	A.SQL_TEXT LIKE 'select%'
AND 	U.USERNAME NOT LIKE 'SYS%'
AND 	P.COST > 4000 
order by P.COST;
